/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.UCB.PS;

/**
 *
 * @author Ninja
 */
public class Soma extends javax.swing.JFrame {

    /**
     * Creates new form Soma
     */
    public Soma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        numero1Label = new javax.swing.JLabel();
        numero1Txt = new javax.swing.JTextField();
        somaButton = new javax.swing.JButton();
        numero2Label = new javax.swing.JLabel();
        numero2Txt = new javax.swing.JTextField();
        resultadoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Calculo"));
        jPanel1.setToolTipText("");
        jPanel1.setAutoscrolls(true);
        jPanel1.setName("Calculo de Soma"); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numero1Label.setText("Numero-1");
        jPanel1.add(numero1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, -1, -1));

        numero1Txt.setColumns(5);
        numero1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numero1TxtActionPerformed(evt);
            }
        });
        jPanel1.add(numero1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 16, -1, -1));

        somaButton.setText("Soma");
        somaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                somaButtonMouseClicked(evt);
            }
        });
        jPanel1.add(somaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        numero2Label.setText("Numero-2");
        jPanel1.add(numero2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 19, -1, -1));

        numero2Txt.setColumns(5);
        jPanel1.add(numero2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 16, -1, -1));

        resultadoLabel.setText("Resultado");
        resultadoLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(resultadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, 29));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numero1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numero1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numero1TxtActionPerformed

    private void somaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_somaButtonMouseClicked
        //get number
        double N1 = Double.parseDouble(numero1Txt.getText());
        double N2 = Double.parseDouble(numero2Txt.getText());
        //set resultado
        String resultado;
        resultado = String.valueOf(N1+N2);
        resultadoLabel.setText(resultado);
    }//GEN-LAST:event_somaButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel numero1Label;
    private javax.swing.JTextField numero1Txt;
    private javax.swing.JLabel numero2Label;
    private javax.swing.JTextField numero2Txt;
    private javax.swing.JLabel resultadoLabel;
    private javax.swing.JButton somaButton;
    // End of variables declaration//GEN-END:variables
}
